### ISSUE TITLE
Table 'shop.confirm_links' doesn't exist

### ISSUE THREAD

**Issue by binaryjc** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#10]
An error occurred upon ordering a product.  sql dump file might be outdated?

INSERT INTO `confirm_links` (`link`, `for_order`) VALUES ('b32b34e77178a22906292252dcc5db96', 1235)
Filename: models/Publicmodel.php
Line Number: 303

**Comment by kirilkirkov** [comment]
@binaryjc Hello. Sorry about this. I add table to sql dump file with this commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/611a0d545abcde929241491a9e1c5d3a7cedd243
