### ISSUE TITLE
Discount Codes

### ISSUE THREAD

**Issue by jackttcoms** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#12]
Do u have discount codes integrated and what about a demo?

**Comment by kirilkirkov** [comment]
@jackttcoms Hello. No for now dont have discount codes but i will add it and when done i will tell you

**Comment by kirilkirkov** [comment]
@jackttcoms Discount coupon functionality is added with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/e97903de27f8f0f6e5cdc1135be222a673ccc6ec
