### ISSUE TITLE
How to add discount coupon?

### ISSUE THREAD

**Issue by ateebahmed** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#13]

**Comment by kirilkirkov** [comment]
@ateebahmed Hello. For now the system dont support discount codes. When i add this functionality i will tell you here.

**Comment by kirilkirkov** [comment]
@ateebahmed Discount coupon functionality is added with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/e97903de27f8f0f6e5cdc1135be222a673ccc6ec

**Comment by kirilkirkov** [comment]
@ateebahmed
