### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by vikaskumarmca** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#15]
hi 
thank for sharing good source but i am running this code if am facing index.php problem each and every open page from admin.

http://localhost/shopping/admin/publish  Problem
http://localhost/shopping/index.php/admin/publish right

**Comment by kirilkirkov** [comment]
@vikaskumarmca This is not a problem. You can load admin/publish with index.php before and without :).
