### ISSUE TITLE
Table 'ci_ecom.confirm_links' doesn't exist

### ISSUE THREAD

**Issue by terrauser1** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#16]
INSERT INTO `confirm_links` (`link`, `for_order`) VALUES ('a33ae444a460438dba0fdd5403d32e0a', 1236)

**Comment by murad288** [comment]
[confirm_links.zip](https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/files/1224429/confirm_links.zip)
add a table name 'confirm_links ' with two fields link, for_order in your mysql database.
simply download the sql zip file and extract a sql file.
then import the sql file into your database.

**Comment by kirilkirkov** [comment]
@terrauser1 Sorry about this. I add it with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/611a0d545abcde929241491a9e1c5d3a7cedd243
@murad288 Thanks for help
