### ISSUE TITLE
chrome refuse to execute language file all.js due to invalid mime type

### ISSUE THREAD

**Issue by murad288** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#17]
When i run this cms in my local xampp server, it works fine. but when i run in remote server with chrome browser, it refuse to execute language js file all.js.
![capture8](https://user-images.githubusercontent.com/30503629/29306903-62b373d6-81c1-11e7-8be0-93b6b30905cc.JPG)

As a result, BUY or ADD TO SHOPPING CART not work.
at present the language js file all.js called by loader controller.
After huge google search and some research, it can be solved by the following way:

create a language folder into assets folder and.. folder strcture is
assets
--language
----englisg
------js
--------all.js
now it works in chrome

if any body has another solution, pls reply.

**Comment by kirilkirkov** [comment]
@murad288 Hello. The problem is because when browser load javascript file it comes with wrong header - text/html. It must be application/javascipt. I was fix this with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/d2ad93dab23a92650bff20a5a56762d25648c1c8
