### ISSUE TITLE
How to run on localhost

### ISSUE THREAD

**Issue by NgKhanh** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#18]
At step 3, i set config base_url is empty but it dont work

`$config['base_url'] = '';`

**Comment by kirilkirkov** [comment]
@NgKhanh There you must set your url to the site without directories.

**First way is:**
Copy source code in root localhost directory and in $config['base_url'] set http://localhost/

**Second way is:**
Set up virtual host. 
Explain how to set up virtual host with apache and ubuntu:
https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts

**Comment by laayis** [comment]
@kirilkirkov I have cloned the repo. When i try to asses it i can pull css, what am i doing wrong? I have set my Base Url like this $config['base_url'] = 'http://localhost/shoppingcart/'; "shoppingcart" is what i renamed the clone repo to.

**Comment by kirilkirkov** [comment]
@laayis website do not have to be in a directory. Copy the source to root directory of yours localhost and set in $config['base_url']  = ''http://localhost/';

**Comment by kirilkirkov** [comment]
@laayis 
@NgKhanh 

I will give you fix. Set .htaccess file to this:

**RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]**

**Comment by laayis** [comment]
Thanks it worked.

**Comment by laayis** [comment]
1 more question, I don't have table confirm_links. As i was following the Buy journey, once i put in my details and click  button "Make Order", i get this error **'trueinc.confirm_links' doesn't exist**. Please advice.

**Comment by kirilkirkov** [comment]
@laayis I was added table **confirm_links** with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/611a0d545abcde929241491a9e1c5d3a7cedd243

You can create it with following query:

CREATE TABLE `confirm_links` (
  `id` int(11) NOT NULL,
  `link` char(32) NOT NULL,
  `for_order` int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by MiniKamra** [comment]
@kirilkirkov i have the similar problem as @laayis had, 

I have cloned the repo. When i try to asses the site over the browser it i cannot pull the css, what am i doing wrong? I have set my Base Url like this $config['base_url'] = 'http://localhost/shoppingcart/'; "shoppingcart" is what i renamed the clone repo to.

after adding the following in .htaccess file 

RewriteEngine on
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^(.*)$ index.php?/$1 [L]

CSS is still not showing. I can not have the application in root folder as have other projects also.

**Comment by kirilkirkov** [comment]
Answer - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/issues/22

**Comment by staycoolz** [comment]
> But you will must set this directory in css files for images because this will not load.. :)
> 
> Example:
> 
> .avatar {
> background-image: url("/assets/imgs/login-cover.png");
> }
> 
> TO:
> 
> .avatar {
> background-image: url("/shop/assets/imgs/login-cover.png");
> }


i still dont get it where file should i edit the css

**Comment by staycoolz** [comment]
![image](https://user-images.githubusercontent.com/26382192/30521482-5df344be-9bea-11e7-91eb-9a8b58c02d2c.png)


please help me anyone :)

**Comment by kirilkirkov** [comment]
Can you send me screenshot from from browser network stat? (right click in the browser, click Inspect, click Network, refresh page)

**Comment by vlahx** [comment]
@Kiril and @laayis 
I use that 
`$config['base_url'] = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$config['base_url'] .= "://".$_SERVER['HTTP_HOST'];
$config['base_url'] .= str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);`
instead `$config['base_url']` and works very good. This stops problems like that, and we have a good path for everything, including assets, and solve problem for some problems like this user @NgKhanh

**Comment by kirilkirkov** [comment]
@vlahx  Yes, this is good solution. But I do not understand why they do not create Virtual Hosts? This is the right way and is as close as possible to a real environment.
@staycoolz Check your **$config['base_url']** and if there are not set only domain (without directory /myshopfolder) like virtual host, just remove from .htaccess file **RewriteBase /** .

**Comment by vlahx** [comment]
@kiril, 
When you try to delete a language already added, you obtain an error like this

> Error Number: 1054
> Unknown
> column

>  'bg' in 'where clause'

> DELETE FROM translations WHERE abbr = bg

> Filename: modules/admin/models/Adminmodel.php

> Line Number: 163

I think you didnt know about that yet
I modified the function in Adminmodel.php and loooks like below and works.

`public function deleteLanguage($id)
    {
        $this->db->select('abbr');
        $this->db->where('id', $id);
        $res = $this->db->get('languages');
        $row = $res->row_array();
        $this->db->trans_start();
        $this->db->query('DELETE FROM languages WHERE id = ' . $this->db->escape($id));
        $this->db->query("DELETE FROM translations WHERE abbr =  '$row'");
        $this->db->query("DELETE FROM cookie_law_translations WHERE abbr = '$row'");
        $this->db->trans_complete();
        if ($this->db->trans_status() === FALSE) {
            return false;
        }
        return true;
    }`
I changed the query for delete translations and cookie_law_translations a little bit
I hope is useful

**Comment by cbarrette361** [comment]
Hi I received this error :

An uncaught Exception was encountered

Type: Error

Message: Call to a member function result() on array

Filename: /var/www/html/shop/application/core/MY_Controller.php

Line Number: 98

Backtrace:

File: /var/www/html/shop/application/core/MY_Controller.php
Line: 82
Function: getAllLangs

File: /var/www/html/shop/application/core/MY_Controller.php
Line: 29
Function: loadVars

File: /var/www/html/shop/application/controllers/Home.php
Line: 39
Function: render

File: /var/www/html/shop/index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
I made some changes to the code and I forgot to fix it. Is ready - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/2323cf98326ce1943e14a1fe5e7b0e4a1fd26ea1
