### ISSUE TITLE
Choose Payment Method

### ISSUE THREAD

**Issue by laayis** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#19]
Why is the choose payment method stuck on Cash On Delivery? Please advice. I would like to use bank and paypal.

**Comment by kirilkirkov** [comment]
To use paypal and bank you must go to administration -> orders -> settings, then set business email address for paypal and click Save
To use bank payments also must set your bank details in "Bank Account Settings" and they will show in checkout page.
