### ISSUE TITLE
problem on running on local host

### ISSUE THREAD

**Issue by MiniKamra** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#22]
@kirilkirkov i have the similar problem as @laayis had,

I have cloned the repo. When i try to asses the site over the browser it i cannot pull the css, what am i doing wrong? I have set my Base Url like this $config['base_url'] = 'http://localhost/shoppingcart/'; "shoppingcart" is what i renamed the clone repo to.

after adding the following in .htaccess file

RewriteEngine on
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^(.*)$ index.php?/$1 [L]

CSS is still not showing. I can not have the application in root folder as have other projects also.

**Comment by kirilkirkov** [comment]
@MiniKamra If you use Linux are you sure that have rights to css files?
What errors give you apache logs? (if you use apache)

Ok, you also can add virtual host/domain to point to this directory :)
