### ISSUE TITLE
The Cart library is deprecated. Are you using it?

### ISSUE THREAD

**Issue by danielzilli** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#24]
The current CI Cart library is deprecated and it will be remove on the next CI updates. 
https://www.codeigniter.com/userguide3/libraries/cart.html

Are you using the Cart library?

**Comment by kirilkirkov** [comment]
@danielzilli I know that this library is deprecated and i don't use it.

**Comment by ariandi22** [comment]
@danielzilli  So, what is deprecated actually mean? in latest release it's still there but it's also said that "should not be used."

**Comment by kirilkirkov** [comment]
@ariandi22 They will be stop updates for bugs or vulnerabilities. It is good to be not used. Its not hard to create custom Cart Library.

**Comment by bigkiandi** [comment]
@kirilkirkov alright i’m really upset for it. My project are going to be done but my freind show me the official documentation that said it’s should not to be used. It’s screwed me up.
