### ISSUE TITLE
Table questions 

### ISSUE THREAD

**Issue by satrianivzla** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#25]
Hi there
Your Shopping runs good,  just need to check the following things
a.- css, js and images files are inside public folder then file SL.php need to be updated.
b.- Checking your shopping.sql looks like there is no table questions required to the FAQ section.

Cheers!

**Comment by kirilkirkov** [comment]
@satrianivzla 
a. What is SL.php file? :)
