### ISSUE TITLE
Delete languages already added

### ISSUE THREAD

**Issue by vlahx** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#26]
@kiril,
When you try to delete a language already added, you obtain an error like this

Error Number: 1054
Unknown
column
'bg' in 'where clause'
DELETE FROM translations WHERE abbr = bg
Filename: modules/admin/models/Adminmodel.php
Line Number: 163
I think you didnt know about that yet
I modified the function in Adminmodel.php and loooks like below and works.

`public function deleteLanguage($id) { $this->db->select('abbr'); $this->db->where('id', $id); $res = $this->db->get('languages'); $row = $res->row_array(); $this->db->trans_start(); $this->db->query('DELETE FROM languages WHERE id = ' . $this->db->escape($id)); $this->db->query("DELETE FROM translations WHERE abbr = '$row'"); $this->db->query("DELETE FROM cookie_law_translations WHERE abbr = '$row'"); $this->db->trans_complete(); if ($this->db->trans_status() === FALSE) { return false; } return true; `}`
I changed the query for delete translations and cookie_law_translations a little bit
I hope is useful

**Comment by kirilkirkov** [comment]
@vlahx I fix it - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/5d23bf67c1166dbfafe3d07157f5e90d86183019
