### ISSUE TITLE
Login and registration

### ISSUE THREAD

**Issue by jkkenzie** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#28]
Do you have a login and registration modules for this?

**Comment by kirilkirkov** [comment]
@jkkenzie Hello. No system dont support this, but soon maybe will be added.

**Comment by jkkenzie** [comment]
No worries, It has a good checkout process, I consider the best I have seen so far. Thanks for the good work!

**Comment by kirilkirkov** [comment]
@jkkenzie  Greetings!

**Comment by kirilkirkov** [comment]
@jkkenzie it is added
