### ISSUE TITLE
Item Click 

### ISSUE THREAD

**Issue by evilnohds** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#29]
Clicking on an item or product information pulls up the latest item saved and not the selected item. Product URL for every item is the same on the DB. Thanks.

**Comment by kirilkirkov** [comment]
@evilnohds Iam sorry. Very stupid bug :) . Fixed with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/ba4f35af914c95b3dd76518abdfa027a2bcd7a62

**Comment by evilnohds** [comment]
Thanks for the immediate action. Very nice job on this!
