### ISSUE TITLE
How to set default language to English?

### ISSUE THREAD

**Issue by keystroke99** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#30]
Hi.. just installed the project... really cool and interesting.. i'm struggling to change the default language to english. please help me with this.

**Comment by kirilkirkov** [comment]
Hello @keystroke99 .
Go to application/config/config.php and change this three lines:

**$config['language'] = 'bulgarian';
$config['language_abbr'] = 'bg';
$config['currency'] = 'лв';
$config['currencyKey'] = 'BGN';**

to English.

**Comment by kirilkirkov** [comment]
I change default language to English

**Comment by keystroke99** [comment]
Thank you.
