### ISSUE TITLE
Error in query (1364): Field 'last_login' doesn't have a default value

### ISSUE THREAD

**Issue by keystroke99** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#31]
i'm getting this error while uploading the SQL file to my database.
please check it

**Comment by kirilkirkov** [comment]
@keystroke99  - fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/4353b4ecfca10d00509dc72c702d043ee18d0786
