### ISSUE TITLE
Virtual products

### ISSUE THREAD

**Issue by vlahx** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#34]
@kiril, any ideeas for create virtual products as books(epub) or others?
I am thinking how to modify the code to do that.
Thanks in advance !!!

**Comment by kirilkirkov** [comment]
@vlahx what do you mean by virtual products? can an example
Did you mean this like attached file? What is your idea 
![product-virtual-membership](https://user-images.githubusercontent.com/3421328/32332558-79bb5196-bfee-11e7-9292-dcb049acb2a0.png)

**Comment by vlahx** [comment]
I mean put products for download. As books for download

**Comment by kirilkirkov** [comment]
But how you will know when client is make payment? You can publish online book like e normal product and when payment is ready you can just send link like email to user to download it.

**Comment by kirilkirkov** [comment]
If you receive paypal payments you can add to paypal_success.php file some marker and if product is downloadable to get out link for it in this page. hmm you also can add to admin/orders page, when mark payment as Processed to check products and when some of them is downloadable to be sended link to user email. But you must also set email like required filed in checkout page

**Comment by vlahx** [comment]
Sounds good what you say, it is a good ideea. I thinking at something like after paying, generate a link and offer to the buyier to download. But your ideea is excellent. I will use it

**Comment by kirilkirkov** [comment]
I will add virtual products support after some time :)

**Comment by vlahx** [comment]
Thank you much, Kiril !!! I just wanted an ideea from you how to modify the code.

**Comment by kirilkirkov** [comment]
Something like this (you may think more about it):

- Add to sql table products column "downloadable" like varchar
- Add downloadable filed in /admin/views/ecommerce/publish.php
- Then add book and set in this filed link for download (you can create folder and upload books from file manager in administration)
- Add in /admin/conrollers/ecommerce/Orders.php - changeOrdersOrderStatus() , when $result is true get products from this order ID and if some of them have filed "downloadable" that is not null.. send link from it to email address in this order.

I think something like this will be more easy..
