### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by jayvi** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#37]
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: third_party/MX/Base.php

Line Number: 55

since i switch to test env.

DEV ENV : 

A PHP Error was encountered

Severity: Warning

Message: mysqli::real_connect(): (28000/1045): Access denied for user 'root'@'localhost' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 201

Backtrace:

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Loader.php
Line: 109
Function: DB

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Loader.php
Line: 65
Function: initialize

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Base.php
Line: 55
Function: __construct

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Base.php
Line: 60
Function: __construct

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Controller.php
Line: 4
Function: require

File: /usr/share/nginx/www/caseland.store/public_html/application/third_party/MX/Modules.php
Line: 123
Function: include_once

File: /usr/share/nginx/www/caseland.store/public_html/application/core/MY_Controller.php
Line: 4
Function: spl_autoload_call

File: /usr/share/nginx/www/caseland.store/public_html/index.php
Line: 293
Function: require_once

**Comment by jayvi** [comment]
trying to run on nginx server

**Comment by kirilkirkov** [comment]
@jayvi  go to application/config/database.php and set 

       **'hostname' => 'localhost',
	'username' => 'root',
	'password' => 'toor',
	'database' => 'shop',**

**Comment by jayvi** [comment]
already did that just the problem came from some other place

**Comment by kirilkirkov** [comment]
@jayvi The system cant find your sql server.

**Comment by kirilkirkov** [comment]
@jayvi  Maybe your password is wrong because message is "Access denied for user 'root'@'localhost' (using password: YES)"

**Comment by jayvi** [comment]
no its not i just setup clean CI and it's working. Anyway i was hope to use the platform cause its look very promising but i guess will need to write my own :)

**Comment by kirilkirkov** [comment]
@jayvi Okey :) But the problem is not from the platform. CodeIgniter connection type is same like clean downloded CI setup.
If your server is linux set **hostname to localhost** !

**Comment by jayvi** [comment]
yeah agree may be will debug it later :)

**Comment by vlahx** [comment]
If you use a clean CI, maybe you need some autoload helpers or libraries. Its indicated to use all download from Kiril, and remember, there is a HMVC CI, you have a lot of errors in MX Third_party.
