### ISSUE TITLE
SQL Issues

### ISSUE THREAD

**Issue by dhistira** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#39]
This query:

`CREATE TABLE IF NOT EXISTS `orders` ( `id` int(10) unsigned NOT NULL AUTO_INCREMENT, `order_id` int(11) NOT NULL, `products` text NOT NULL, `date` int(10) unsigned NOT NULL, `referrer` varchar(255) NOT NULL, `clean_referrer` varchar(255) NOT NULL, `payment_type` varchar(255) NOT NULL, `paypal_status` varchar(10) DEFAULT NULL, `processed` tinyint(1) NOT NULL DEFAULT '0', `viewed` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'viewed status is change when change processed status', `confirmed` tinyint(1) NOT NULL DEFAULT '0', `discount_code` varchar(20) NOT NULL PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1`

And this is the issue
3 errors were found during analysis.

A comma or a closing bracket was expected. (near "(" at position 572)
Unexpected beginning of statement. (near "`id`" at position 573)
Unrecognized statement type. (near "ENGINE" at position 581)

**Comment by kirilkirkov** [comment]
@dhistira Its fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/4348d81d8d18161306a73520468663a2a1245ad2
