### ISSUE TITLE
id Column in Some Table are not in Auto Increment

### ISSUE THREAD

**Issue by dhistira** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#40]
Some id Column in some table aren't auto increment, made some issues when editing status because duplicating of 0 value.

List of table with id not auto increment:
orders_clients
bank_accounts
confirm_links
vendors_orders_clients

**Comment by kirilkirkov** [comment]
@dhistira  Its fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/b993d54b82396f1b9c5cb3f160f3329d732887b7 
Thanks!
