### ISSUE TITLE
Error on importing database.sql

### ISSUE THREAD

**Issue by ang3lx** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#42]
Query SQL:

CREATE TABLE `vendors` (
  `id` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `url` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8
Messaggio di MySQL: Documentazione

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by kirilkirkov** [comment]
@ang3lx I cant reproduce this error. Okey, just create like this:

```
CREATE TABLE vendors (
id int(11) NOT NULL,
name varchar(50) DEFAULT NULL,
url varchar(50) NOT NULL,
email varchar(50) NOT NULL,
password varchar(100) NOT NULL,
updated_at varchar(50) DEFAULT NULL,
created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

updated_at is not used anywhere in interface for the now...
