### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by egulfam** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#43]
I am trying to download the zip file but it restarts after reaching 4 MB. I don't know why it is happening.

**Comment by kirilkirkov** [comment]
@egulfam Go here and download it - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/archive/master.zip 
Try from another browser..I can not do anything with Github :)
