### ISSUE TITLE
Product image is not showing in admin as well fronend

### ISSUE THREAD

**Issue by bssolet** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#44]
Hi.. I have uploaded a product but product image is not showing in admin as well as frontend
http://prntscr.com/hpx7zu
http://prntscr.com/hpx8pb
http://prntscr.com/hpx9ip

i think the issue is appearing do to using "DIRECTORY_SEPARATOR forward slash" if i change it to "/" then image are showing correctly.
please advise what i have to do ..
please help

**Comment by kirilkirkov** [comment]
@bssolet Yes! This is the problem. Fix it to you to dont block your working.. i will commit fixed version this month

**Comment by kirilkirkov** [comment]
@bssolet Its fixed with - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/f50f1888ac66f791a718edfe2974afaf7650a849
Sorry about this nooob bug.
