### ISSUE TITLE
SQL errors

### ISSUE THREAD

**Issue by danielzilli** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#46]
When I try to import the database.sql file into my DB, I get these errors:

[ERROR in query 20] Incorrect table definition; there can be only one auto column and it must be defined as a key
[ERROR in query 21] Table 'supershop.users_public' doesn't exist

**Comment by kirilkirkov** [comment]
@danielzilli  Fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/638e240f98492f6548359fec2d0120aa1af9f3e7
