### ISSUE TITLE
How to setup Paypal Api payment gateway

### ISSUE THREAD

**Issue by locvfx** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#47]
Hi,
I found a section to activate PayPal payment gateway  at the URL: /admin/orders?settings
However, I could not setup Paypal API user and secret key in the admin dashboard. Is it in the source code, if yes, where is the location of configuration file?
Could you please guide me.
Thanks

**Comment by locvfx** [comment]
Btw, regardless submit my Paypal sandbox token, I just tried to checkout the cart and I got the error from Paypal sandbox:
"Things don't appear to be working at the moment. Please try again later."

**Comment by kirilkirkov** [comment]
@locvfx There just set you email address and currency (like EUR) and when user click to pay from paypal he will be redirected to the paypal site. There is no need api secret key

**Comment by kirilkirkov** [comment]
Sandbox mode must be activated from your user account in paypal get "fake" email and pass.

**Comment by kirilkirkov** [comment]
@locvfx configuration file is in application/views/templates/YOURTEMPLATE/checkout_parts/paypal_payment.php
