### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by MarcoPiarulli** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#48]
First of all, thanks for the wonderful program.
Now the question, is there any way to set a language other than English as the default language?
Thank you

**Comment by kirilkirkov** [comment]
@MarcoPiarulli  Hello. Thanks.
Open application/config/config.php and change lines:
_$config['language'] = 'english';
$config['language_abbr'] = 'en';
$config['currency'] = '€';
$config['currencyKey'] = 'EUR';_
with your parameters. 
Your language must be added from the administration of the site - admin/languages. 
That's it :)
