### ISSUE TITLE
Shop only for registered users

### ISSUE THREAD

**Issue by MarcoPiarulli** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#49]
Is it possible to enable shopping only for registered users?

**Comment by kirilkirkov** [comment]
@MarcoPiarulli  No, but easy can do it. Go to administration settings (admin/settings) and set to On "Multi-Vendor Support" after that set some SESSION check in "checkout" page. If user is not logged redirect to login page.

**Comment by kirilkirkov** [comment]
it is added
