### ISSUE TITLE
Template folder is missing

### ISSUE THREAD

**Issue by kkrsanthosh** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#5]
Dear kirilkirkov,
thanks for all your efforts for developing this shopping cart script.
But the template folder in root directory is missing. Could you please upload it?
Thanks and regards,
Santhosh.

**Comment by rajvanshipradeep15** [comment]
Hello Kirilkirkov,
Some of the files are missing, I will post the list which I think is missing from the repository.

http://shop.com/templatecss/custom.css"
http://shop.com/cssloader/theme.css"
http://shop.com/loadlanguage/all.js"
http://shop.com/templatejs/mine.js"
http://shop.com/attachments/site_logo/NewLogo.jpg"
http://shop.com/template/imgs/green-basket.png"
http://shop.com/template/imgs/shopping-cart-icon-515.png"
http://shop.com/template/imgs/search-ico.png"
http://shop.com/loadlanguage/all.js"
http://shop.com/template/imgs/shopping-cart-icon-515.png"
http://shop.com/template/imgs/green-basket.png"
http://shop.com/attachments/site_logo/NewLogo.jpg"
http://shop.com/template/imgs/search-ico.png"
http://shop.com/templatejs/mine.js"

**Comment by asimshazad** [comment]
Dear kirilkirkov,
As mentioned by @kkrsanthosh ,templatecss folder is missing,would you be able to add that?

**Comment by pradho** [comment]
Dear kirilkirkov,
As mentioned by @kkrsanthosh and mentioned again @asimshazad  ,templatecss folder is missing,would you be able to add that?

**Comment by kirilkirkov** [comment]
@asimshazad @kkrsanthosh @pradho   there is no templatecss folder :) this is just route that point to Loader controller who gets css file from choosed templated. You can see this in /application/config/routes.php ->
// Template Routes
$route['template/imgs/(:any)'] = "Loader/templateCssImage/$1";
$route['templatecss/imgs/(:any)'] = "Loader/templateCssImage/$1";
$route['templatecss/(:any)'] = "Loader/templateCss/$1";
$route['templatejs/(:any)'] = "Loader/templateJs/$1";
