### ISSUE TITLE
404 error on show product

### ISSUE THREAD

**Issue by MarcoPiarulli** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#51]
Hi,
when I click on a product to show the details, I get a 404 error.
The link is something like /ANTAB222_213 where 213 is products.id

I have tried also /home/viewProduct/213 and /shop-product_213 but I get always 404 error

What I can check? Thank's

P.S. All others routing work correct, the .htaccess is NOT modified and mod_rewrite is active

**Comment by kirilkirkov** [comment]
@MarcoPiarulli hmm Its strange. Do you use standard .htaccess file and /application/confi/routes.php? 
Try to edit this file - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/blob/master/application/controllers/Home.php 
and in viewProduct() just comment line 100 ( show_404(); ) and try to see you call this method from your url. If do not call it you must check your .htaccess file and routes.php if you have changes there.
Or if you call this method.. hmm check the sql statement and why cant find the product.

Hmm if you are remove the category for this product maybe this is the reason. Check that this product have category that is present.
