### ISSUE TITLE
Brand Index

### ISSUE THREAD

**Issue by evilnohds** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#52]
Hi. When publishing or updating a product, brand index is not saved on DB so it's always zero and therefore clicking on a brand name will not pull up products associated with it. Also, a product or products will only show when its category or the parent of that category is clicked - only on two levels. Is it possible for you to fix this so that all the way up to the highest category they would still show when said category is clicked? Oh and can't edit languages on admin panel, but of course it works when changed from site_lang.php. Thank you.

**Comment by kirilkirkov** [comment]
Brand problem is fixed with commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/83c32dddc7983b3dd0406b3b49db3790b46ca43b

hmm. maybe cant edit languages because do not have permissions on server directory? Please check it.

**Comment by evilnohds** [comment]
Thank you for the timely action on the problem. Nice work. Keep it up.
