### ISSUE TITLE
unable to change default Language

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#55]
Im trying to change the default Language currency from $ to £ and also change the image

There is no way to create a new language and set the new language as default

**Comment by kirilkirkov** [comment]
@matthaselip Fist add new language from administration Languages and make sure that you are give 777 permissions (on linux) for your attachments directory and application/languages directory. After you add this language go to /application/config/config.php and fill this with your new language

$config['language'] = 'english';
$config['language_abbr'] = 'en';
$config['currency'] = '€';
$config['currencyKey'] = 'EUR';
