### ISSUE TITLE
viewing product price currency shows Euro

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#56]
I have changed the default language currency (via the backend) to GB/GBP
When viewing products, the price currency shows as Euro's

Ideally i need all prices to be £ british pound sterling

**Comment by kirilkirkov** [comment]
@matthaselip When change language and currency here
$config['language'] = 'english';
$config['language_abbr'] = 'en';
$config['currency'] = '€';
$config['currencyKey'] = 'EUR';

and in Languages table in database set the currency for this language you will see it in your products
