### ISSUE TITLE
adding product fields

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#57]
is it easy to add product fields to the add a new product page?  i would like to add Size/Weight plus some more possibly.

**Comment by kirilkirkov** [comment]
@matthaselip Yes, its easy. Open application/modules/admin/views/ecommerce/publish.php and add

```
    <div class="form-group for-shop">
        <label>Size/Weight</label>
        <input type="text" placeholder="Size/Weight" name="size" value="<?= @$_POST['size'] ?>" class="form-control">
    </div>
``` 
After that open application/modules/admin/models/Products_model.php  and in setProduct add again size filed "'size' => $post['size']," to update and insert query. Next open your database and in products table add new column size. And final you must add this column to the view in template that use.
