### ISSUE TITLE
change around the price,currency to currency, price on the view product page

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#58]
currently the view product page shows the price as: price/currency.  which view file is this so we can swap them around to show: currency/price?
![image](https://user-images.githubusercontent.com/6297790/36233295-2ad546a4-11dd-11e8-8e6a-2a41b5ffa0f0.png)

**Comment by kirilkirkov** [comment]
@matthaselip Open view_product.php page and just exchange positions CURRENCY constant and $product['price'] array :)
