### ISSUE TITLE
multi vendor function

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#59]
does the multi vendor function i the system settings work?
i have enabled this feature but unable to see any difference in the administration panel, or on the publish product page as any additional input fields etc...

**Comment by matthaselip** [comment]
im not too sure why you woul want a vendor login from the home page on the shoppingcart if you are selling B2C.  i can understand if its B2B

**Comment by kirilkirkov** [comment]
@matthaselip because if user have account he cant check history of orders .. someday wll be developed

**Comment by kirilkirkov** [comment]
it is added
