### ISSUE TITLE
Clicking on a Category link in https issue

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#60]
When ever you click on a category link when viewing the shopping cart over https, the redirect all ways defaults back to http.  

jquery is submitting a form and sending the data to js function submitForm()

is this a codeigniter issue ot jquery issue?

ps
strangely this also happens to the home link, altthough viewing the html code quite clearly shows as https://

**Comment by kirilkirkov** [comment]
@matthaselip Somewhere you missed changing from http to https. Check the code from where the redirect comes from.
