### ISSUE TITLE
adding a new produt against a shop category/sub category

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#61]
You cant identify which category a sub category is assigned to.  if you have the same name sub category but in different categories.

The Drop down should show category -> sub category so that you can easily assign a product to the correct sub category, otherwise you would have to guess...

**Comment by kirilkirkov** [comment]
There is no category logic in the sub category to have the same name. You can easily change the code when viewing products at all levels of the category.
