### ISSUE TITLE
Postage and Packaging

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#62]
I cant find anywhere in the admin to manage postage and packaging?  the only option i can find is to give free postage if postae >= number (in the settings tab)

We should be able to add different postage costs depending on the cost of the shopping cart.

**Comment by kirilkirkov** [comment]
@matthaselip There is no option for this. You have "Free Shipping for order equal or more than:" in Settings on Administration. Add your own column in orders table and field in checkout page if you want it

**Comment by matthaselip** [comment]
would it be possible if you could tell me which files i need to change in order to add a postage and packaging in the form of a drop down box?  for example. standard delivery £3.99 or next day £11.99

Thank you for your continuous support :)

**Comment by kirilkirkov** [comment]
@matthaselip  First you need to add POST field in your template "application/views/templates/templatename/checkout.php" there is a post form and you must add the html. Next in application/models/Public_model.php in method "setOrder" must add insert and update lines of this filed from html form. And final part is to add columns in mysql table.

**Comment by matthaselip** [comment]
thank you i have done this.  do i need to change paypal code to ensure that it passing postage and packaging to paypal?

**Comment by kirilkirkov** [comment]
I think that only the final price for payment without details is submitted to pepal

**Comment by matthaselip** [comment]
ok great, so when populating the final price i just need to add the values of the postage field?

**Comment by kirilkirkov** [comment]
@matthaselip yes
