### ISSUE TITLE
some files are missing ..

### ISSUE THREAD

**Issue by mohsin980** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#63]
What am I trying to do..
..What's happening
![image](https://user-images.githubusercontent.com/25708165/36383601-7642ab98-15ae-11e8-89ce-f3d900fc7ed4.png)

**Comment by kirilkirkov** [comment]
@mohsin980 go to README.md and read "Easy installation in 3 steps". There she writes how to start the app if you want her to stay in a directory

These errors are because your site address is localhost/Shopping-Cart....
Create virtual host and point it to Shopping Cart directory.

**Comment by kirilkirkov** [comment]
@mohsin980 Nothing missing. Just set virtual host ;)

**Comment by dcr2018** [comment]
Hi, I'm having the same problem. I create a virtual host but still some files are missing. 
![files not found](https://user-images.githubusercontent.com/37335617/38140809-db01796c-340b-11e8-9bda-17700a7e9637.png)

**Comment by kirilkirkov** [comment]
Check in application/config/config.php  - base_url  - http://tienda.casa
Check you .htaccess file is there.
