### ISSUE TITLE
adding a product with no images

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#64]
adding a product with no image displays a broken image on the home page.  when you re edit that product and add an image and re load the view product, the product shows a 2 images, 1st image broken and the 2nd image as the new image but the home page shows tthe broken 1st image

**Comment by kirilkirkov** [comment]
@matthaselip which template use?

**Comment by matthaselip** [comment]
ive figured it out.  it was the redlabel template.   i have amended the view_product.php file 
`            <?php
            if(strlen($product['image']) > 0) {
            ?>
            <div <?= $product['folder'] != null ? 'style="margin-bottom:20px;"' : '' ?>>
                <img src="<?= base_url('/attachments/shop_images/' . $product['image']) ?>" style="width:auto; height:auto;" data-num="0" class="other-img-preview img-responsive img-sl the-image" alt="<?= str_replace('"', "'", $product['title']) ?>">
            </div>
            <?php
            } else {
                // show default no image supplied
                ?>
                <img src="<?=base_url('/assets/imgs/no-image.png')?>" class="img-responsive"/>
                <?php
            }`
created an image no-image.png
