### ISSUE TITLE
shopping cart issue - adding quantity greater than product quantity set

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#65]
shopping cart, clicking the + sign to increment the quantity against that product. 
this allows you to set the quantity greater than the quantity available set against the product in the edit product screen.  every time the quantity is incremented a check should be done against the quantity in stock, that way people cant order more than the stock level

**Comment by kirilkirkov** [comment]
@matthaselip I will fix it soon.

**Comment by matthaselip** [comment]
i will look into it :)

**Comment by kirilkirkov** [comment]
@matthaselip Your fast fix - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/b069e84dd0d655265ce632695cd7b444834df430
