### ISSUE TITLE
error when clockingg on Make order from the checkout page

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#66]
after clicking on 'make order' from the checkout page the following errors occur

File: C:\wamp\www\codeignitershop\application\views\templates\redlabel\checkout_parts\paypal_payment.php
Line: 33
Function: convertCurrency

File: C:\wamp\www\codeignitershop\application\third_party\MX\Loader.php
Line: 355
Function: include

File: C:\wamp\www\codeignitershop\application\third_party\MX\Loader.php
Line: 294
Function: _ci_load

File: C:\wamp\www\codeignitershop\application\core\MY_Controller.php
Line: 50
Function: view

File: C:\wamp\www\codeignitershop\application\controllers\Checkout.php
Line: 146
Function: render

File: C:\wamp\www\codeignitershop\index.php
Line: 292
Function: require_once

0.00">
A PHP Error was encountered
Severity: Notice

Message: Undefined offset: 1

Filename: helpers/currency_convertor_helper.php

Line Number: 11

Backtrace:

File: C:\wamp\www\codeignitershop\application\helpers\currency_convertor_helper.php
Line: 11
Function: _error_handler

File: C:\wamp\www\codeignitershop\application\views\templates\redlabel\checkout_parts\paypal_payment.php
Line: 33
Function: convertCurrency

File: C:\wamp\www\codeignitershop\application\third_party\MX\Loader.php
Line: 355
Function: include

File: C:\wamp\www\codeignitershop\application\third_party\MX\Loader.php
Line: 294
Function: _ci_load

File: C:\wamp\www\codeignitershop\application\core\MY_Controller.php
Line: 50
Function: view

File: C:\wamp\www\codeignitershop\application\controllers\Checkout.php
Line: 146
Function: render

File: C:\wamp\www\codeignitershop\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
@matthaselip Fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/046ed2107f45c237af2a49d7f7bbb3752d826a85
When pass same currency $from, $to we dont neet to try to convert.

**Comment by matthaselip** [comment]
i think this occurred because the languages is set to $ and the config is set to £

**Comment by kirilkirkov** [comment]
Message: Undefined offset: 1
Filename: helpers/currency_convertor_helper.php
Undefined offset i s $converted[1].
You pass same currency and google (realtime) convertor return nothing. Example - https://finance.google.com/finance/converter?a=22&from=BGN&to=BGN :) Your currency must be valid FROM , TO

**Comment by matthaselip** [comment]
so, if $from != $to, then go ahead and convert, else carry on with the script :)

**Comment by kirilkirkov** [comment]
Yes. Convert only if need to do it :)
