### ISSUE TITLE
a message when trying to edit default Language

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#67]
I am trying to change the values for the default language selected, but there is no sibmit button and an error message
![image](https://user-images.githubusercontent.com/6297790/36482139-26ed7c3c-170a-11e8-8313-4bed3fc46ab0.png)

**Comment by kirilkirkov** [comment]
please try to find a solution yourself before asking for anything :)

https://www.google.bg/search?client=firefox-b&dcr=0&ei=j3WNWti6F4emsgGahKmoDQ&q=max_input_vars+php++limit&oq=max_input_vars+php++limit&gs_l=psy-ab.3...2818.2818.0.2886.1.1.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..1.0.0....0.ezu0YwyqHKY

**Comment by matthaselip** [comment]
i found a solution, just wanted to notify you incase anybody else would also get this issue ;)

**Comment by kirilkirkov** [comment]
@matthaselip Thanks. This is default value for **max_input_vars** and that's the reason I put the message
