### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by cookiesze** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#69]
A PHP Error was encountered
Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 190
Function: library

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 65
Function: initialize

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Base.php
Line: 55
Function: __construct

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Base.php
Line: 60
Function: __construct

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Controller.php
Line: 4
Function: require

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Modules.php
Line: 123
Function: include_once

File: /home/maneepow/domains/maneepower.com/public_html/test/application/core/MY_Controller.php
Line: 4
Function: spl_autoload_call

File: /home/maneepow/domains/maneepower.com/public_html/test/index.php
Line: 292
Function: require_once

An uncaught Exception was encountered
Type: Exception

Message: Session: Configured save path '' is not a directory, doesn't exist or cannot be created.

Filename: /home/maneepow/domains/maneepower.com/public_html/test/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 138

Backtrace:

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 173
Function: _ci_load_library

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 190
Function: library

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 153
Function: libraries

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Loader.php
Line: 65
Function: initialize

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Base.php
Line: 55
Function: __construct

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Base.php
Line: 60
Function: __construct

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Controller.php
Line: 4
Function: require

File: /home/maneepow/domains/maneepower.com/public_html/test/application/third_party/MX/Modules.php
Line: 123
Function: include_once

File: /home/maneepow/domains/maneepower.com/public_html/test/application/core/MY_Controller.php
Line: 4
Function: spl_autoload_call

File: /home/maneepow/domains/maneepower.com/public_html/test/index.php
Line: 292
Function: require_once

**Comment by cookiesze** [comment]
Server version: 5.6.34

**Comment by matthaselip** [comment]
this could be because of the environment.   check which php version your using, looks like you may not have write access to the cache folder.  possibly a codeigniter issue not a shopping cart issue :)

**Comment by kirilkirkov** [comment]
@cookiesze It is codeigniter problem. Check google - https://www.google.bg/search?client=firefox-b-ab&dcr=0&ei=sHueWu2oEMzwgAaWkKGwDw&q=codeigniter+warning+Session_files_driver.php&oq=codeigniter+warning+Session_files_driver.php&gs_l=psy-ab.3..0i203k1j0i22i30k1l9.19856.22601.0.22719.21.21.0.0.0.0.162.2134.10j10.20.0....0...1c.1.64.psy-ab..1.20.2131...0j35i39k1j0i67k1j0i131k1j0i22i10i30k1.0.9S32R7k0UXo
