### ISSUE TITLE
error when removing item from shopping cart

### ISSUE THREAD

**Issue by matthaselip** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#70]
the following error occurs when removing an item from the shopping cart, i assume if the session has expired (user has been on page for a long time)

A PHP Error was encountered
Severity: Warning

Message: array_unique() expects parameter 1 to be array, null given

Filename: libraries/ShoppingCart.php

Line Number: 66

Backtrace:

File: C:\wamp\www\codeignitershop\application\libraries\ShoppingCart.php
Line: 66
Function: array_unique

File: C:\wamp\www\codeignitershop\application\core\MY_Controller.php
Line: 27
Function: getCartItems

File: C:\wamp\www\codeignitershop\application\controllers\Checkout.php
Line: 53
Function: render

File: C:\wamp\www\codeignitershop\index.php
Line: 292
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: current() expects parameter 1 to be array, null given

Filename: models/Public_model.php

Line Number: 265

Backtrace:

File: C:\wamp\www\codeignitershop\application\models\Public_model.php
Line: 265
Function: current

File: C:\wamp\www\codeignitershop\application\libraries\ShoppingCart.php
Line: 66
Function: getShopItems

File: C:\wamp\www\codeignitershop\application\core\MY_Controller.php
Line: 27
Function: getCartItems

File: C:\wamp\www\codeignitershop\application\controllers\Checkout.php
Line: 53
Function: render

File: C:\wamp\www\codeignitershop\index.php
Line: 292
Function: require_once

**Comment by kirilkirkov** [comment]
hmm, its strange. I think that is right check - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/cceb024ae62e5e80854c2ae33ba75567ab1425f0
