### ISSUE TITLE
Shop Page on Greenlabel Template Error Not Found 404

### ISSUE THREAD

**Issue by ariqcahya** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#71]
I tried to acces shop url in greenlabel themes example http://localhost/mydomain/shop,
i found "The page you requested was not found."
what i can do to access this page?
i found shop.php in greenlabel template but i dont know how  to view it

**Comment by matthaselip** [comment]
sounds like this is an environment setup rather than the shopping cart setup.  ensure the config variables are setup correctly/.htaccess   running in a folder rather than root can cause some complications.
