### ISSUE TITLE
error in URLs

### ISSUE THREAD

**Issue by dcr2018** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#72]
Hi, there is an error in my application I can't figure out. All the links in the frontend and in the backend as well are like this:
tienda.casa/shop
tienda.casa/blog
tienda.casa/admin/blog
tienda.casa/admin/pages
but none of these links work. If I add index.php to the URL, then it works. For example:
tienda.casa/index.php/admin/settings

**Comment by kirilkirkov** [comment]
Check your .htaccess file
