### ISSUE TITLE
the templates are not showing correctly

### ISSUE THREAD

**Issue by dcr2018** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#73]
Hi, thank you for answering my questions. It seems that some files are missing. When I open the shop in the browser, it says it can't load the following files:
http://tienda.casa/templatecss/custom.css
http://tienda.casa/loadlanguage/all.js
http://tienda.casa/templatejs/mine.js
http://tienda.casa/attachments/banners/1.jpg
http://tienda.casa/attachments/banners/2.jpg
http://tienda.casa/loadlanguage/all.js

I tried commenting "RewriteBase /" in .htaccess and also I created a virtual host for the shop but still I'm getting this error message.
If I look into the project's folder I see there is no templatecss, no loadlanguage, nor templatejs folders. What should I do?

There are other pages with missing files. In the admin panel, template, the thumbnails are not showing.
This file is missing: http://tienda.casa/Loader/templateCssImage/screenshot.png/clothesshop

**Comment by kirilkirkov** [comment]
@dcr2018 templatecss is not a directory. This url call templateCssImage method in Loader controller and he search for "custom.css" file in application/views/templates/templatename/assets/css/custom.css. If this file is not there you can get 404. Please check your permissions if you are using linux. It you use windows server try to replace "DIRECTORY_SEPARATOR" constant with "/" in Loader controller.
This bug is not from shopping cart system i think .

**Comment by dcr2018** [comment]
I found the problem. The htaccess files were disabled in my server. Now everything works! :smile: 

This is the default configuration in Ubuntu so if someone is having the same problem, you have to look in apache2.conf, and look at the section that looks like this:
<Directory /path/to/your/Document/Root>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

The option AllowOverride must be "All". This way you enable htaccess files.

Thanks for the help! :smile:

**Comment by mullernato** [comment]
I have same problem, but with Nginx. Help please.

**Comment by kirilkirkov** [comment]
@mullernato Make sure that .htaccess file is in use. "The option AllowOverride must be "All"."

**Comment by chrisastley** [comment]
@mullernato you need to configure your nginx config file for the rewrites. I had to replace my existing root location block with this.

`    index index.html index.php;

    include /etc/nginx/block_bots.conf-include;
	
	# if your default controller is something other than "welcome" you should change the following
	if ($request_uri ~* ^(/home(/index)?|/index(.php)?)/?$)
	{
		rewrite ^(.*)$ / permanent;
	}

	# removes trailing "index" from all controllers
	if ($request_uri ~* index/?$)
	{
		rewrite ^/(.*)/index/?$ /$1 permanent;
	}

	# removes trailing slashes (prevents SEO duplicate content issues)
	if (!-d $request_filename)
	{
		rewrite ^/(.+)/$ /$1 permanent;
	}

	# removes access to "system" folder, also allows a "System.php" controller
	if ($request_uri ~* ^/system)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}

	# unless the request is for a valid file (image, js, css, etc.), send to bootstrap
	if (!-e $request_filename)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}`

**Comment by mullernato** [comment]
@chrisastley Please help me. Is this my configuration file correct?

```
server {
    listen 80;
    server_name shop.loc;

    root /home/computy/www/shop;
   
    index index.html index.php;

	# if your default controller is something other than "welcome" you should change the following
	if ($request_uri ~* ^(/home(/index)?|/index(.php)?)/?$)
	{
		rewrite ^(.*)$ / permanent;
	}

	# removes trailing "index" from all controllers
	if ($request_uri ~* index/?$)
	{
		rewrite ^/(.*)/index/?$ /$1 permanent;
	}

	# removes trailing slashes (prevents SEO duplicate content issues)
	if (!-d $request_filename)
	{
		rewrite ^/(.+)/$ /$1 permanent;
	}

	# removes access to "system" folder, also allows a "System.php" controller
	if ($request_uri ~* ^/system)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}

	# unless the request is for a valid file (image, js, css, etc.), send to bootstrap
	if (!-e $request_filename)
	{
		rewrite ^/(.*)$ /index.php?/$1 last;
		break;
	}

    location / {
     	 try_files $uri $uri/ /index.php?/$request_uri;
    }

    error_page 404 /404.html;

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location ~ \.php$ {
        include fastcgi_params;
        include php7-fastcgi.conf;
    }

    location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
        expires max;
        log_not_found off;
    }

    location ~ /\.ht {
        deny all;
    }
    
    location /RequestDenied {
        return 406;
    }

}
```

**Comment by chrisastley** [comment]
@mullernato 

Remove this part;
`    location / {
     	 try_files $uri $uri/ /index.php?/$request_uri;
    }`

I'd previously said to replace the Root location block and you still have it
