### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by abhisheksharma85** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#75]
Hey, 
I wanted to try out your shopping cart to learn coding. I was able to setup and run but page is not very clean as it is missing lots of files.
![screen shot 2018-04-09 at 1 35 40 pm](https://user-images.githubusercontent.com/319746/38521627-1670621e-3bfb-11e8-9501-5f39583d5694.png)

**Comment by kirilkirkov** [comment]
@abhisheksharma85 Are you sure that you have working .htaccess file and you have correct base_url in application/config/config.php ?
