### ISSUE TITLE
issue with order details information

### ISSUE THREAD

**Issue by dcr2018** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#76]
Hello,

I'm using greenlabel template. When I create orders, I can see the order in the dashboard panel. But if I click on More Info button, I don't see the products list. This only happens when I'm using greenlabel template; with the other templates the info is displayed correctly. I attach some screenshots.

![orden-clothesshop-editado-ok](https://user-images.githubusercontent.com/37335617/38699442-6a66f570-3e6e-11e8-9a97-bfc33dc16af5.png)

![orden-greenlabel-editado-no](https://user-images.githubusercontent.com/37335617/38699271-eeeb362c-3e6d-11e8-8bed-15229f55c30c.png)

![orden-onepage-editado-ok](https://user-images.githubusercontent.com/37335617/38699276-f1bcc46a-3e6d-11e8-96fb-93216ea7914d.png)

![orden-redlabel-editado-ok](https://user-images.githubusercontent.com/37335617/38699278-f4c7fea4-3e6d-11e8-9d1d-06f623ba7421.png)

**Comment by kirilkirkov** [comment]
@dcr2018 Fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/12d3a099fe97a198ff649b392f77dab277ae87c3 
the problem was that input product fields were out of form on the checkout page

**Comment by kirilkirkov** [comment]
@dcr2018 also check this - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/4ba485c2c4129fba4c225dc65648436c7b54a49a
