### ISSUE TITLE
database given is not proper with code

### ISSUE THREAD

**Issue by vishu10193** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#77]
Error Number: 1146

Table 'ecom.vendors' doesn't exist

SELECT `vendors`.`url` as `vendor_url`, `products`.`id`, `products`.`quantity`, `products`.`image`, `products`.`url`, `products_translations`.`price`, `products_translations`.`title`, `products_translations`.`old_price` FROM `products` LEFT JOIN `products_translations` ON `products_translations`.`for_id` = `products`.`id` LEFT JOIN `vendors` ON `vendors`.`id` = `products`.`vendor_id` WHERE `products_translations`.`abbr` = 'en' AND `visibility` = 1 AND `quantity` >0 ORDER BY `products`.`procurement` DESC LIMIT 5

Filename: C:/xampp/rock/application/models/Public_model.php

Line Number: 445

**Comment by kirilkirkov** [comment]
CREATE TABLE `vendors` (
  `id` int(11) NOT NULL,
  `name` varchar(50) DEFAULT NULL,
  `url` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(100) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Vendors table is in database.sql file. I dont understand the problem @vishu10193 ?

**Comment by vishu10193** [comment]
I think Sir the issue is

MySQL said: Documentation

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause 

CREATE TABLE  `vendors` (

 `id` INT( 11 ) NOT NULL ,
 `name` VARCHAR( 50 ) DEFAULT NULL ,
 `url` VARCHAR( 50 ) NOT NULL ,
 `email` VARCHAR( 50 ) NOT NULL ,
 `password` VARCHAR( 100 ) NOT NULL ,
 `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
 `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = INNODB DEFAULT CHARSET = utf8;

**Comment by kirilkirkov** [comment]
@vishu10193 Can you please tell me what do you do to get this error? I cant reproduce :)

**Comment by kirilkirkov** [comment]
@vishu10193 You make update for?

**Comment by kirilkirkov** [comment]
Here is explained - https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-5.html
This limitation, which was only due to historical, code legacy reasons, has been lifted in recent versions of MySQL.
Update your mysql :)) or just remove from updated_at current_timestamp
