### ISSUE TITLE
incomplete code

### ISSUE THREAD

**Issue by vthinkmehul** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#79]
hello,,,
i setup your code but many file missing mainly admin

please help

**Comment by kirilkirkov** [comment]
@vthinkmehul Give me an example. What missing?

**Comment by vthinkmehul** [comment]
https://www.screencast.com/t/YoXyMs88x69
https://www.screencast.com/t/scvPbW7zb
https://www.screencast.com/t/eEtY0689vSqb

**Comment by kirilkirkov** [comment]
@vthinkmehul 
https://www.screencast.com/t/YoXyMs88x69 
templatecss, cssloader,loadlanguage  are a routes, not real folder - 
$route['templatecss/imgs/(:any)'] = "Loader/templateCssImage/$1";
$route['templatecss/(:any)'] = "Loader/templateCss/$1";
$route['cssloader/(:any)'] = "Loader/cssStyle";
$route['loadlanguage/(:any)'] = "Loader/jsFile/$1";

https://www.screencast.com/t/scvPbW7zb
right way is to use the shop in clean domein - kwikbucket.com , not - kwikbucket.com/ci , if want to be in directory /ci read the text after  "Easy installation in 3 steps"  here - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter 

https://www.screencast.com/t/eEtY0689vSqb
there are NO admin folder... admin is in /application/modules/admin :)) this is HMVC , not MVC.

have a nice day
