### ISSUE TITLE
added product is not showing in user templet

### ISSUE THREAD

**Issue by BlackBeardo** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#8]
I setup everything. working fine. 

So I added one category(mobile) first. then added product(iphone).

go to site and checked. category name is showing up. but iphone is not showing up on hamepage. or I clicked it in mobile category. still nothing.

**Comment by vikaskumarmca** [comment]
how to setup.

**Comment by kirilkirkov** [comment]
@BlackBeardo Do you still have this problem?
@vikaskumarmca You can see the guide how to setup in description of repository - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter
