### ISSUE TITLE
elfinder config not working

### ISSUE THREAD

**Issue by loginetsolutions** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#80]
Using file manager http://localhost/shop/admin/filemanager
give me elfinder configuration error in console
elfinder debug: [error] [elfinder] Invalid backend configuration.<br>Readable volumes not available.

**Comment by loginetsolutions** [comment]
I know the path is not OK. I have figured out this but I need help to configure the right path. 
Testing on XAMPP localhost Windows
Thanks

**Comment by loginetsolutions** [comment]
Yes, after update to elFinder-2.1.38 and change the \application\modules\admin\views\advanced_settings\filemanager.php everything is OK. Thanks.

**Comment by kirilkirkov** [comment]
@loginetsolutions You are welcome
