### ISSUE TITLE
Convert currency in publish product is not working anymore

### ISSUE THREAD

**Issue by loginetsolutions** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#81]
Convert currencies from Google finance is not working anymore.
Changed currency_convertor_helper for
<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

function convertCurrency($amount, $from, $to)
{
    if ($from == $to) {
        return number_format(round($amount, 3), 2);
    }
    $data = json_decode(file_get_contents("https://free.currencyconverterapi.com/api/v5/convert?q=".$from."_".$to."&compact=y"));
    
	$currencies = $from."_".$to;
        $rate = $data->$currencies->val;
	$converted = $amount * $rate;
    return number_format(round($converted, 3), 2);
}

**Comment by kirilkirkov** [comment]
@loginetsolutions Yes. Google finance will not working and with this commit - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/0e0e1326851c554e25792b13d6a5441444d02072 i remove currency convertor. Now paypal currency will be get from selected site language

**Comment by loginetsolutions** [comment]
I just changed the helper to other url:
`function convertCurrency($amount, $from, $to)
{
    if ($from == $to) {
        return number_format(round($amount, 3), 2);
    }
    $data = json_decode(file_get_contents("https://free.currencyconverterapi.com/api/v5/convert?q=".$from."_".$to."&compact=y"));
    
	$currencies = $from."_".$to;
    $rate = $data->$currencies->val;
	$converted = $amount * $rate;
    return number_format(round($converted, 3), 2);
}`

**Comment by kirilkirkov** [comment]
@loginetsolutions ok, its fine while working and this api :)
