### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by yudikondo** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#82]
Message: __autoload() is deprecated
Filename: PHPMailer/PHPMailerAutoload.php

**Comment by kirilkirkov** [comment]
This function - http://php.net/manual/en/function.autoload.php (__autoload()) is deprecated in php 7.2. You can edit PHPMailer/PHPMailerAutoload.php line to spl_autoload_register(). Can you try? I wait for your reply.

**Comment by yudikondo** [comment]
Hi @kirilkirkov i did not test but is not it better use the Composer?

**Comment by kirilkirkov** [comment]
@yudikondo yes its better

**Comment by kirilkirkov** [comment]
spl_autoload_register() insteat __autoload() is your fix for php 7.2
