### ISSUE TITLE
__autoload() is deprecated, use spl_autoload_register() instead

### ISSUE THREAD

**Issue by jt890** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#86]
Hi Im new to codeigniter. But i know a little bit of it. I have this problem can you please tell me how to fix it thanks .
![image](https://user-images.githubusercontent.com/40785772/42201918-4847b166-7ecc-11e8-878c-ad0025f0aefa.png)

**Comment by kirilkirkov** [comment]
@jt890 Try to replace __autoload() with spl_autoload_register() in application/libraries/PHPMailer/PHPMailerAutoload.php at line 45 (bottom of the code).

what is the php version you use?

**Comment by jt890** [comment]
Wow! Thanks :D solved my problem it was so simple .
