### ISSUE TITLE
Forgot Password not working

### ISSUE THREAD

**Issue by anand1100** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#87]
I trying to send email after clicking on forgot password
but email not going please help me sir.

**Comment by kirilkirkov** [comment]
@anand1100  This functionality is not completed.

**Comment by anand1100** [comment]
Okay Sir Thank Your .

**Comment by kirilkirkov** [comment]
@anand1100  i will fix vendor password recovery now

**Comment by kirilkirkov** [comment]
@anand1100 Not forgot password working ;) https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/bfb063707f290af056a20e6a7cfef151b7b75f71

**Comment by kirilkirkov** [comment]
@anand1100 i add this functionality
https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/552cbc73fdd498db34bd96aa55ae03820d0b2255
