### ISSUE TITLE
Is there any user account?

### ISSUE THREAD

**Issue by anand1100** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#88]
Hello sir , 
Is there any user account that user will get notified that they ordered and can see the status of that product?

**Comment by kirilkirkov** [comment]
Every admin user can get notifications. Go to admin/adminusers , click edit on the user, set Notifications filed to 1 and click save.
You can get all users that must be notified from Public_model->getNotifyUsers();, ,this will return you array, you can loop it in Checkout controller after set_order method and send email with SendEmail library :)

**Comment by kirilkirkov** [comment]
@anand1100 Fixed - https://github.com/kirilkirkov/Shopping-Cart-Solution-CodeIgniter/commit/1bdf04ab98c211f276be06b795c6c9878c150b0e
