### ISSUE TITLE
email not sending to gmail or any other once user book any product for confirmation

### ISSUE THREAD

**Issue by anand1100** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#89]
$this->mail = new PHPMailer;
        //$this->mail->SMTPDebug = 2; 
        //$this->mail->isMail();                                      // Set mailer to use SMTP
        $this->mail->Host = 'just49.justhost.com';                  // Specify main and backup SMTP servers
        $this->mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
        $this->mail->Port = 26;                                    // TCP port to connect to
        $this->mail->SMTPAuth = true;                               // Enable SMTP authentication
        $this->mail->Username = '********@*******.com';                 // SMTP username
        $this->mail->Password = '******';                           // SMTP password

**Comment by kirilkirkov** [comment]
@anand1100 "once user book any product for confirmation" ??

**Comment by anand1100** [comment]
Yes sir I want that if user has book they get email

**Comment by kirilkirkov** [comment]
@anand1100 i dont undestand you. Can you explain me

**Comment by kirilkirkov** [comment]
@anand1100 Check logs of apache. Sending confirmation is from phpmailer library and if email is not sended that mean you connection is not configured

**Comment by kirilkirkov** [comment]
@anand1100  must be  $this->mail->isSMTP(); // Set mailer to use SMTP

**Comment by kirilkirkov** [comment]
@anand1100 
Try this configuration:


		$this->mail = new PHPMailer; 
		$this->mail->isSMTP(); 
		// $this->mail->SMTPDebug = 2; 
		$this->mail->Debugoutput = 'html'; 
		$this->mail->Host = 'smtp.gmail.com'; 
		$this->mail->Port = 587; 
		$this->mail->SMTPSecure = 'tls'; 
		$this->mail->SMTPAuth = true; 
		$this->mail->Username = "email@gmail.com"; 
		$this->mail->Password = "yourpass";
		$this->mail->CharSet = 'UTF-8';
