### ISSUE TITLE
Users must register with shop before purchase

### ISSUE THREAD

**Issue by darknfaze007** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#90]
I must say a big Thank you for having this open to the world...

I just want to know if you may add a feature that requires users to have an account with the shop before they can order.

Well done and God bless your work.

**Comment by kirilkirkov** [comment]
for the moment I will not add it as a function because there is no time but you can easily put a check in the Checkout Controller and if the user is not logged in (there is no session $ _SESSION ['logged_user']), you send it to the login page

**Comment by kirilkirkov** [comment]
@darknfaze007  The functionality of users registration is added. Now you can use it
