### ISSUE TITLE
Hello, I want know how can I add the size color for product?

### ISSUE THREAD

**Issue by higoalespn** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#91]
I trying to do add the size to the product, but I find I can't add it.

**Comment by kirilkirkov** [comment]
I do not think I've added a size, but you can add
"    <div class="form-group for-shop">
        <label>Size</label>
        <input type="text" placeholder="size" name="size" value="<?= @$_POST['size'] ?>" class="form-control" id="size">
    </div>"
to "publish" view and then put a new column size in the "products" table
