### ISSUE TITLE
Image in the admin user code

### ISSUE THREAD

**Issue by surepeps** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#94]
Am sorry for posting this here but i really need your help please can you get me the code to add image to the admin user page please i really need it and also i thank you for the great work you have done it makes people work easier and faster

**Comment by kirilkirkov** [comment]
just 

1. add <input type="file" name="userimage"> to adminUsers.php view
2. add to Adminusers.php controller - 
$config['upload_path'] = './attachments/users/';
			$config['allowed_types'] = 'PNG, JPG';
			$config['remove_spaces'] = TRUE;
			$this->load->library('upload', $config);
			$this->upload->initialize($config);
			if (!$this->upload->do_upload('userimage')) {
				var_dump($this->upload->display_errors()); 
			}
3. after that save to database file name and get it in admin panel. Its easy

**Comment by biasijunior** [comment]
I just wan't to say thank @kirilkirkov for great work you have done (you are doing) you have really helped some of us a lot! thank you 👏🏼

**Comment by kirilkirkov** [comment]
greetings :)) @biasijunior

**Comment by biasijunior** [comment]
greeting it is my pleasure getting a reply from you  @kirilkirkov  :)
