### ISSUE TITLE
Independent language settings

### ISSUE THREAD

**Issue by oldcastlehq** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#96]
Is it possible to set different languages at the same time. For example, the frontend is in Spanish, the backend is in English and a vendor uses French.

**Comment by kirilkirkov** [comment]
@oldcastlehq yes, it is possible but .. the most fast type (noob) is to check url address and if is Vendor (for example) to set French language. You can check in language library (application/library/language) maybe..
