### ISSUE TITLE
Gateway timeout on my live (online) server

### ISSUE THREAD

**Issue by surepeps** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#97]
I tried to upload the codes exactly the way to said we should do but anytime I load the page it shows gateway timeout I mean on my live server (online)...

**Comment by matthaselip** [comment]
This sounds like an environment setup issue.  Check for things such as max execution time or max input time in php.ini.

Check prerequisites for hosting codeigniter

**Comment by surepeps** [comment]
There is no php.ini in the cpanel and is there any other way solve this problem

**Comment by matthaselip** [comment]
You can change ini congutation in the php script. Call them at the top of your index.php file

**Comment by matthaselip** [comment]
You can change ini congutation in the php script. Call them at the top of your index.php file

**Comment by kirilkirkov** [comment]
@surepeps This is not software problem

**Comment by surepeps** [comment]
Thanks have done it
