### ISSUE TITLE
mkdir(): Permission denied

### ISSUE THREAD

**Issue by felisane** [kirilkirkov/Shopping-Cart-Solution-CodeIgniter#99]
I don´t know how to fix this error

**Comment by matthaselip** [comment]
Hi Felisane

It looks like that codeigniter does not have the necessary access to create a folder in your environment.

check that user:group has access.  if you have command line, use chown then use chmod and ensure folders have 755 and files have 644

**Comment by kirilkirkov** [comment]
@felisane  Yes, thats it , that @matthaselip  says
